#!/bin/bash

current=$(adb shell dumpsys power | grep mHoldingDisplaySuspendBlocker | cut -d'=' -f2)

echo "mHoldingDisplaySuspendBlocker is: $current"
echo "Changing status..."

if test $current = "false"; then
	adb shell dumpsys battery plug
	adb shell dumpsys deviceidle unforce
	adb shell input keyevent 26
	adb shell dumpsys deviceidle get deep
else
	adb shell dumpsys deviceidle disable
	adb shell dumpsys deviceidle enable
	adb shell dumpsys battery unplug
	adb shell input keyevent 26
	adb shell dumpsys deviceidle force-idle
	adb shell dumpsys deviceidle get deep
fi
