#!/bin/bash

set -eux

minutes=$2
goal=$1

hours=$(echo "scale=2; $minutes / 60" | bc)

result=$(bmndr $goal $hours)

zenity --info --text="Beeminder datapoint sent successfully: $hours hours to $goal" &

sleepin $minutes
