#!/bin/bash

set -x

export DISPLAY=:0

previous=$(cat ~/.watch-disp-conf.txt)
current=$(xrandr -q | md5sum)

test "$previous" = "$current"
result=$?

xrandr -q | md5sum > ~/.watch-disp-conf.txt

exit $result
