#!/bin/bash

set -eux

function warn() {
	zenity --warning --text "$@"
	echo "$@"
}

function notif() {
	notify-send "$@"
	echo "$@"
}

DELAY_MINUTES=$1

test "$DELAY_MINUTES" -gt 0 || { notif "Incorrect delay: $DELAY_MINUTES"; exit 1; }

test "$DELAY_MINUTES" -eq 1 || notif "Going to sleep in $DELAY_MINUTES minutes"

let DELAY_MINUTES--

sleep "$DELAY_MINUTES"m

warn "Going to sleep in 1 minute" &
sleep 30s

for i in $(seq 1 6 | tac); do
	let TIMELEFT=i*5
	notif "Going to sleep in $TIMELEFT seconds"
	sleep 5
done

#/etc/pm/sleep.d/20_force-quit

#sudo pm-suspend
#sudo acpitool -S
gnome-screensaver-command -l
