#!/bin/bash
set -eux
current_ws=$(wmctrl -d | grep '*' | awk '{print $1}')
sleep 1
echo $current_ws
windows_on_current_ws=$(wmctrl -l | awk "{if (\$2 == $current_ws) print \$1;}")
for w in $windows_on_current_ws ; do
	wmctrl -i -c $w
done
